language: node_js
dist: trusty
sudo: required
node_js: 10
install:
  - npm install -g purescript bower pulp
  - npm install
script:
  - bower install --production
  - pulp build
  - bower install
  - pulp test
